[package]
name = "rcurl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.2"
futures-util = "0.3.14"
indicatif = "0.15.0"
reqwest = { version = "0.11.3", features = ["stream"] }
tokio = { version = "1.13.0", features = ["full"] }

