[package]
name = "aim"
version = "1.8.1"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ðŸŽ¯ A command line download/upload tool with resume."
categories = [
    "HTTP client",
    "command-line-utilities",
    "network-programming",
    "web-programming::http-client"
]

keywords = [ 
    "cli",
    "download",
    "resume",
    "upload"
]

repository = "https://github.com/mihaigalos/aim"
license = "MIT"

[dependencies]
async-ssh2-lite = { version = "0.4", features = ["tokio"] }
async-std = "1.12.0"
async-stream = "0.3.3"
async_ftp = "6.0.0"
autoclap = "0.3.12"
clap = { version = "4.1.1", features = ["cargo", "string"] }
crossbeam-utils = "0.8.14"
custom_error = "1.9.2"
dotenvy = "0.15.6"
futures = "0.3"
futures-util = "0.3.25"
http = "0.2.8"
indicatif = "0.17.3"
lazy_static = "1.4.0"
log = "0.4.17"
melt = "0.1.6"
native-tls = "0.2"
netrc = "0.4.1"
openssl = { version = "0.10.45", features = ["vendored"] }
question = "0.2.2"
regex = "1.7.1"
reqwest = { version = "0.11.13", features = ["stream"] }
rust-s3 = { version = "0.31.0", features = ["blocking"] }
self_update = { version = "0.34.0", features = ["archive-tar", "compression-flate2"] }
sha2 = "0.10.6"
skim-navi = "0.1.4"
ssh2 = "0.9.3"
strfmt = "0.2.2"
tokio = { version = "1.24.2", features = ["full"] }
tokio-util = {version="0.7.4", features = ["full"]}
untildify = "0.1.1"
url-parse = "1.0.3"
uuid = { version = "1.2", features = ["v4"] }
warpy = "0.3.4"

[dev-dependencies]
serial_test = "1.0.0"
