[package]
name = "aim"
version = "1.4.0"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ðŸŽ¯ A command line download/upload tool with resume."
categories = [
    "HTTP client",
    "command-line-utilities",
    "network-programming",
    "web-programming::http-client"
]
keywords = [ 
    "cli",
    "download",
    "resume",
    "upload"
]
repository = "https://github.com/mihaigalos/aim"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-io = "1.3"
async-ssh2-lite = { git = "https://github.com/mihaigalos/async-ssh2-lite" }
async-std = "1.11.0"
async-stream = "0.3.2"
async_ftp = "6.0.0"
autoclap = "0.2.2"
clap = { version = "3.1.8", features = ["cargo"] }
custom_error = "1.9.2"
dotenv = "0.15.0"
futures = "0.3"
futures-util = "0.3.14"
http = "0.2.7"
indicatif = "0.16.2"
log = "0.4.17"
melt = "0.1.6"
native-tls = "0.2"
netrc = "0.4.1"
openssl = { version = "0.10.40", features = ["vendored"] }
openssl-src = "300.0.5"
question = "0.2.2"
reqwest = { version = "0.11.3", features = ["stream"] }
rust-s3 = { version = "0.31.0", features = ["blocking"] }
self_update = { version = "0.30.0", features = ["archive-tar", "compression-flate2"] }
sha2 = "0.10.0"
ssh2 = "0.9.3"
strfmt = "0.1.6"
tokio = { version = "1.14.0", features = ["full"] }
tokio-util = {version="0.6.9", features = ["full"]}
url = { git = "https://github.com/mihaigalos/rust-url#a3bd6f3ce67e2ca10312a254e9666c923e3a1fa0" }
uuid = { version = "0.8", features = ["v4"] }
warpy = "0.2.1"

regex = "1.5.4" # Remove this dep once this is merged: https://github.com/sathishsoundharajan/untildify/pull/2
#untildify = "0.1.0" Remove comment once this is merged: https://github.com/sathishsoundharajan/untildify/pull/2

[dev-dependencies]
serial_test = "0.5.1"
